# Source: jxboot-helmfile-resources/templates/jx-gcjobs-cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-gcjobs
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  schedule: "0/30 */3 * * *"
  startingDeadlineSeconds: 4000
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: gcjobs
            release: jxboot-helmfile-resources
          annotations:
        spec:
          restartPolicy: Never
          serviceAccountName: jx-gcjobs
          containers:
            - name: gcjobs
              command: [jx]
              args:
                - gitops
                - gc
                - jobs
                - --namespace
                - jx-git-operator
              imagePullPolicy: IfNotPresent
              image: "ghcr.io/jenkins-x/jx-boot:3.2.402"
              env:
                - name: JX_LOG_FORMAT
                  value: json
                - name: JX_LOG_LEVEL
                  value: info
                - name: PIPELINE_KIND
                  value: dummy
              resources: {}
