# Source: docker-registry/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry-secret
  namespace: jx
  labels:
    app: docker-registry
    chart: docker-registry-2.1.0
    heritage: Helm
    release: docker-registry
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"docker-registry-secret","properties":[{"name":"haSharedSecret","question":"The ha secret","help":"Shared secret for Registry","generator":"password","minLength":16,"maxLength":16}],"mandatory":true}'
spec:
  backendType: local
  data:
    - name: haSharedSecret
      key: haSharedSecret
      property: haSharedSecret
    - name: proxyUsername
      key: proxyUsername
      property: proxyUsername
    - name: proxyPassword
      key: proxyPassword
      property: proxyPassword
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'docker-registry'
        secret.jenkins-x.io/schema-object: '{"name":"docker-registry-secret","properties":[{"name":"haSharedSecret","question":"The ha secret","help":"Shared secret for Registry","generator":"password","minLength":16,"maxLength":16}],"mandatory":true}'
      labels:
        app: docker-registry
        chart: docker-registry-2.1.0
        heritage: Helm
        release: docker-registry
    type: Opaque
