# Source: jxboot-helmfile-resources/templates/jx-gcjobs-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gcjobs
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gcjobs
subjects:
  - kind: ServiceAccount
    name: jx-gcjobs
    namespace: jx
